sharimg_default_homepage:
    pattern:  /
    defaults: { _controller: SharimgDefaultBundle:Default:index }
    
sharimg_default_helloworld:
    pattern:  /helloworld
    defaults: { _controller: SharimgDefaultBundle:Default:helloworld }
