parameters:
    sharimg_default.event_listener.class: Sharimg\DefaultBundle\EventListener\ControllerListener

services:
    sharimg_default.event_listener:
        class: %sharimg_default.event_listener.class%
        tags:
          -  { name: kernel.event_listener, event: kernel.controller, method: onCoreController }
