parameters:
    sharimg_user.user_service.class: Sharimg\UserBundle\Service\UserService

services:
    sharimg_user.user_service:
        class: %sharimg_user.user_service.class%
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
