parameters:
#    sharimg_user.example.class: Sharimg\UserBundle\Example

services:
#    sharimg_user.example:
#        class: %sharimg_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
