sharimg_content_homepage:
    pattern:  /contents
    defaults: { _controller: SharimgContentBundle:Default:index }
    
sharimg_content_add:
    pattern:  /content/add
    defaults: { _controller: SharimgContentBundle:Default:add }
    
sharimg_content_random:
    pattern:  /content/random
    defaults: { _controller: SharimgContentBundle:Default:random }

sharimg_content_show:
    pattern:  /show/{content}
    defaults: { _controller: SharimgContentBundle:Default:show }
    
sharimg_content_comment_raw:
    pattern:  /show/{content}/comment_raw
    defaults: { _controller: SharimgContentBundle:Comment:listRaw }
    requirements:
        _method: POST
    options:
        expose: true

sharimg_content_post_comments:
    pattern:  /comments/{content}
    defaults: { _controller: SharimgContentBundle:Comment:post }
    requirements:
        _method: POST
    
sharimg_content_favorite:
    pattern:  /favorites
    defaults: { _controller: SharimgContentBundle:Favorite:list }
    
sharimg_content_favorize_ws:
    pattern:  /ws/favorize.json
    defaults: { _controller: SharimgContentBundle:Favorite:favorizeWS }
    requirements:
        _method: POST
    options:
        expose: true

sharimg_content_moderate:
    pattern:  /admin/content
    defaults: { _controller: SharimgContentBundle:Admin:moderate }

sharimg_api_content_add:
    pattern:  /api/add_content.json
    defaults: { _controller: SharimgContentBundle:Api:add }
    requirements:
        _method: POST
    options:
        expose: true

sharimg_api_content_view:
    pattern:  /api/content.json
    defaults: { _controller: SharimgContentBundle:Api:content }
    
sharimg_api_content_list:
    pattern:  /api/content_list.json
    defaults: { _controller: SharimgContentBundle:Api:list }
    
sharimg_api_moderate_content:
    pattern:  /api/moderate.json
    defaults: { _controller: SharimgContentBundle:Api:moderate }
    requirements:
        _method: POST
    options:
        expose: true
    
sharimg_api_content_favorites:
    pattern:  /api/favorites.json
    defaults: { _controller: SharimgContentBundle:FavoriteApi:list }
    
sharimg_api_content_favorize:
    pattern:  /api/favorize.json
    defaults: { _controller: SharimgContentBundle:FavoriteApi:favorize }
    requirements:
        _method: POST

sharimg_api_content_comment:
    pattern:  /api/comment_list.json
    defaults: { _controller: SharimgContentBundle:CommentApi:list }
    
sharimg_api_content_post_comment:
    pattern:  /api/comment.json
    defaults: { _controller: SharimgContentBundle:CommentApi:post }
    requirements:
        _method: POST
