sharimg_content_homepage:
    pattern:  /
    defaults: { _controller: SharimgContentBundle:Default:index }
    
sharimg_content_add:
    pattern:  /admin/add
    defaults: { _controller: SharimgContentBundle:Admin:add }
