parameters:
    sharimg_content.content_manager.class: Sharimg\ContentBundle\Service\ContentFormHandler

services:
    sharimg_content.content_manager:
        class: %sharimg_content.content_manager.class%
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
