parameters:
#    sharimg_content.example.class: Sharimg\ContentBundle\Example

services:
#    sharimg_content.example:
#        class: %sharimg_content.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
