parameters:
    sharimg_content.content_form_handler.class: Sharimg\ContentBundle\Service\ContentFormHandler

services:
    sharimg_content.content_form_handler:
        class: %sharimg_content.content_form_handler.class%
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
